#!/usr/bin/env ruby

require "tk"

root = TkRoot.new() { title "User Survey" }

gender_frame = TkFrame.new(root) 
age_frame = TkFrame.new(root) 
nation_frame = TkFrame.new(root) 
hobby_frame = TkFrame.new(root) 
yes_no_frame = TkFrame.new(root)
submit_frame = TkFrame.new(root)

lab_age = TkLabel.new(age_frame) do
  text "Age range"
  pack("side"=>"left")
end

lab_gender = TkLabel.new(gender_frame) do
  text "Gender"
  pack("side"=>"left","padx"=>16)
end

lab_nation = TkLabel.new(nation_frame) do
  text "Country"
  pack("side"=>"left","padx"=>18)
end

lab_hobby = TkLabel.new(hobby_frame) do
  text "Hobbies"
  pack("side"=>"left","padx"=>16)
end

gender = TkVariable.new
gender.value = "M"

age = TkVariable.new
age.value = 0..17

newsletter = TkVariable.new
newsletter.value = 1

b_male = TkRadioButton.new(gender_frame) do
  variable gender
  text "Male"
  value "M"
  command { puts "Gender = #{gender.value}" }
  pack("side"=>"left")
end

b_female = TkRadioButton.new(gender_frame) do
  variable gender
  text "Female"
  value "F"
  command { puts "Gender = #{gender.value}" }
  pack("side"=>"left")
end

b_age_017 = TkRadioButton.new(age_frame) do
  variable age
  text "17 or under"
  value 0..17
  command { puts "Age = #{age.value}" }
  pack("side"=>"left")
end

b_age_1850 = TkRadioButton.new(age_frame) do
  variable age
  text "18 to 50"
  value 18..50
  command { puts "Age = #{age.value}" }
  pack("side"=>"left")
end

b_age_51_plus = TkRadioButton.new(age_frame) do
  variable age
  text "51 or over"
  value 51..120
  command { puts "Age = #{age.value}" }
  pack("side"=>"left")
end

nations = %w[ Albania Argentina France Germany 
              Portugal UK USA Uzbekistan ]
nation_list = TkListbox.new(nation_frame, "height"=>3,
                           "selectmode"=>"single",
                           "exportselection"=>0)
nation_list.insert("end", *nations)
nation_scroll = TkScrollbar.new(nation_frame) do
  command { |args| nation_list.yview *args }
  pack("side" => "right", "fill" => "y")
end
nation_list.yscrollcommand {|y0,yn| nation_scroll.set(y0,yn)}
nation_list.pack

hobbies = %w[ Reading Writing Programming Photography 
              TV Movies Concerts Theater Opera Ballet ]
hobby_list = TkListbox.new(hobby_frame,"height"=>5,
                          "selectmode"=>"multiple",
                          "exportselection"=>0)
hobby_list.insert("end", *hobbies)

hobby_scroll = TkScrollbar.new(hobby_frame) do
  command { |args| hobby_list.yview *args }
  pack("side" => "right", "fill" => "y")
end
hobby_list.yscrollcommand {|y0,yn| hobby_scroll.set(y0,yn)}
hobby_list.pack

subscribeBox = TkCheckButton.new(yes_no_frame) do
  variable newsletter
  text "Yes, I want to subscribe to the newsletter."
  command { puts "Subscribe = #{newsletter.value}" }
  pack("side"=>"left")
end

submit_button = TkButton.new(submit_frame) do
  text "Submit"
  command do 
    popup = TkToplevel.new() { title "Your data..."}
    TkLabel.new(popup) do
      your_gender = (gender.value=="M") ? "man" : "woman"
      your_age = case age.value
         when "0..17"           # Notice that these ranges
           "under 18"           # must be expressed as 
         when "18..50"          # strings, because that's
           "between 18 and 50"  # how the TkVariable stores
         when "51..120"         # them.
           "over 50"
         end

      your_nation = 
 if (idx=nation_list.curselection[0]).nil?
   "an unspecified nation"
 else
   nations[idx]
 end
      hobby_array = hobby_list.curselection
      your_hobbies = 
        if hobby_array != []
          hobby_array.map {|x| ' '*24 + hobbies[x]}
        else
          [' '*24 + "None specified."]
        end
      
      notsub = newsletter.value.to_i == 1 ? "" : " not"
      text <<-EOS + your_hobbies.join("\n")
      Our records now show:

        You are a #{your_gender} from #{your_nation},
      and you are #{your_age} years of age.
      You are#{notsub} subscribing to the newsletter.
      Your hobbies are:
 EOS
      justify "left"
      pack("pady"=>10)
    end
    TkButton.new(popup) { text "OK"; command {exit}; pack }
    submit_button.state "disabled"
  end
  pack("side"=>"left")
end

reset_button = TkButton.new(submit_frame) do
  text "Reset"
  command do
    age.value = 0..17
    gender.value = "M"
    newsletter.value = 1
    b_male.focus
  end
  pack("side"=>"left")
end

cancel_button = TkButton.new(submit_frame) do
  text "Cancel"
  command {exit}
  pack
end

gender_frame.pack("anchor"=>"w")
age_frame.pack("anchor"=>"w")
nation_frame.pack("anchor"=>"w")
hobby_frame.pack("anchor"=>"w")
yes_no_frame.pack("anchor"=>"w")
submit_frame.pack

Tk.mainloop
