#!/usr/bin/env ruby

require "tk"

root = TkRoot.new do
  title "Color picker"
  background "gray"
end

c_frame = TkFrame.new(root) { width 200; height 80; pack }

err = TkLabel.new(root) do
  text "Color name or hex value:"
  background "gray"
  pack("pady"=>10)
end

var = TkVariable.new
entry = TkEntry.new(root) do
  width 10
  textvariable var
  pack
end

err = TkLabel.new(root) do
  text ""
  background "gray"
  foreground "red"
  pack
end

disp = TkButton.new(root) do
  text "Display"
  command do
    err.configure("text"=>"")
    color = var.value               # Assume it's a name
    if color =~ /^[0-9a-fA-F]{6}$/  # Prepend # if hex
      color = "#" + color
    end
    begin
      c_frame.configure("background"=>"#{color}")
    rescue => except
      err.configure("text"=>except)
    end
  end
  pack
end

Tk.mainloop
