#!/usr/bin/env ruby

require "tk"

root = TkRoot.new do
  title "Text style picker"
end

tlab = TkLabel.new(root) do
  text "ABC abc 123"
  font "Arial 18"     # Reasonable default
  background "white"
  foreground "red"
  pack
end

fg_frame = TkFrame.new(root)
bg_frame = TkFrame.new(root) 

TkLabel.new(bg_frame) do
  text "Background"
  pack("side"=>"left")
end

bg = TkVariable.new     # Background color
bg.value = "white"
fg = TkVariable.new     # Foreground color
fg.value = "red"
font = TkVariable.new   # Font 
font.value = "Arial"
btext = TkVariable.new  # Bold text
itext = TkVariable.new  # Italic text

err = TkLabel.new(root) do
  text ""
  foreground "red"
  pack
end

# adjust_text is a proc so that (as a closure) it can
# have access to the variables it needs.

adjust_text = proc do
  fontstr = "{#{font.value}} #{size} " + 
            btext.value + " " + itext.value
  begin
    tlab.configure("font"=>fontstr)
    tlab.configure("background"=>bg.value, "foreground"=>fg.value)
  rescue => except
    err.configure("text"=>except)
  end
end

bg_white = TkRadioButton.new(bg_frame) do
  variable bg
  text "White"
  value "white"
  pack("side"=>"left")
end

bg_gray = TkRadioButton.new(bg_frame) do
  variable bg
  text "Gray"
  value "gray"
  pack("side"=>"left")
end

bg_black = TkRadioButton.new(bg_frame) do
  variable bg
  text "Black"
  value "black"
  pack("side"=>"left")
end

TkLabel.new(fg_frame) do
  text "Foreground"
  pack("side"=>"left")
end

fg_red = TkRadioButton.new(fg_frame) do
  variable fg
  text "Red"
  value "red"
  pack("side"=>"left")
end

fg_green = TkRadioButton.new(fg_frame) do
  variable fg
  text "Green"
  value "green"
  pack("side"=>"left")
end

fg_blue = TkRadioButton.new(fg_frame) do
  variable fg
  text "Blue"
  value "blue"
  pack("side"=>"left")
end

bg_frame.pack
fg_frame.pack

entry = TkEntry.new(root) do
  width 9
  textvariable font
  pack
end

size = 18  # Fixed in this example

bold = TkCheckButton.new(root) do
  text "Bold"
  variable btext
  onvalue "bold"
  offvalue ""
  pack
end

italic = TkCheckButton.new(root) do
  text "Italic"
  variable itext
  onvalue "italic"
  offvalue ""
  pack
end

disp = TkButton.new(root) do
  text "Display"
  command { adjust_text.call }
  pack
end

Tk.mainloop