#!/usr/bin/env ruby

require "tk"

op1 = "0"
newnum = [nil]
op2 = opr = nil  # Needed in blocks below.

def digit(display,newnum)
  if newnum[0]
    display.configure("text"=>"0")
    newnum[0] = false
  end
  myval = self.cget("text")
  disp = display.cget("text")
  return if disp == "0" and myval == "0"
  if disp == "0"
    display.configure("text"=>myval)
  else
    display.configure("text"=>(disp+myval))
  end
  display.configure("justify"=>"right")
end

root = TkRoot.new do
  title "Two-function calculator"
  background "gray"
end

display = TkLabel.new(root) do
  text "0"
  width 10
  border 3
  justify "right"
  background "white"
  pack
end

button_frame = TkFrame.new(root) { pack }
num_frame = TkFrame.new(button_frame) { pack("side"=>"left") }
op_frame = TkFrame.new(button_frame) { pack }

b789_frame = TkFrame.new(num_frame) { pack }
b456_frame = TkFrame.new(num_frame) { pack }
b123_frame = TkFrame.new(num_frame) { pack }
b0_frame = TkFrame.new(num_frame) { pack }

num_btn_options = { "height" => 1, "width" => 1, 
                     "background" => "white", 
                     "foreground" => "black"}
op_btn_options = num_btn_options.dup
op_btn_options.update("background"=>"blue",
                       "foreground"=>"white")
eq_btn_options = op_btn_options.dup
eq_btn_options.update("background"=>"darkgreen")
clr_btn_options = op_btn_options.dup
clr_btn_options.update("background"=>"red")

# Note: command HAS to be specified in the block,
# not in the hash, because we call the digit method
# (which references self and thus requires instance_eval).

numbers = []

for num in "0".."9" do
  frame = case num
    when "0" then b0_frame
    when "1".."3" then b123_frame
    when "4".."6" then b456_frame
    when "7".."9" then b789_frame
  end
  numbers << TkButton.new(frame,num_btn_options) do
    text num
    command { digit(display,newnum) }
    pack("side"=>"left")
  end
end
    
b_plus = TkButton.new(op_frame,op_btn_options) do
  text "+"
  command do
    op1 = display.cget("text")
    opr = "+"
    newnum = [true]
  end
  pack
end
b_minus = TkButton.new(op_frame,op_btn_options) do
  text "-"
  command do
    op1 = display.cget("text")
    opr = "-"
    newnum = [true]
  end
  pack
end
b_equal = TkButton.new(op_frame,eq_btn_options) do
  text "="
  command do
    op2 = display.cget("text")
    result = eval("#{op1}#{opr}#{op2}").to_s
    display.configure("text"=>result)
  end
  pack
end
b_clear = TkButton.new(op_frame,clr_btn_options) do
  text "C"
  command { display.configure("text"=>"0") }
  pack
end

Tk.mainloop