#!/usr/bin/env ruby

require 'thread'

def slow_output(msg)
  msg.each_byte do |b|
    print b.chr
    sleep 0.2
    STDOUT.flush
  end
end

m = Mutex.new  # This is the bathroom pass!

print "\nWithout synchronization:\n"
thr1 = Thread.new { slow_output "First " }
thr2 = Thread.new { slow_output "Second " }
thr1.join; thr2.join

print "\nWith synchronization:\n"
thr3 = Thread.new { m.synchronize { slow_output "Third " } }
thr4 = Thread.new { m.synchronize { slow_output "Fourth " } }
thr3.join; thr4.join

print "\nAll done.\n"
