#!/usr/bin/env ruby

# get_via_TCP.rb:

# Receives a line of text through
# a TCP socket, and prints it

require 'socket'

port = 10000

listener = TCPServer.new(port)

sock = listener.accept
input = sock.gets
sock.close

print "Message received: #{input}\n"
