#!/usr/bin/env ruby

# send_via_UDP.rb:
# Sends a line of text, which we hope will 
# be received by the get_via_UDP.rb script

require 'socket'

port = 10001

UDPSocket.new.send("Hello, world.",0,'localhost',port)
