#!/usr/bin/env ruby

# get_via_UDP.rb:
# Receives a line of text through
# a UDP socket and prints it

require 'socket'

port = 10001

sock = UDPSocket.new
sock.bind("localhost",port)

msg = sock.recvfrom(80)  # 80 is maximum message length
puts "message from #{msg[1][2]} on port #{msg[1][1]}: '#{msg[0]}'"
