#!/usr/bin/env ruby

require 'gtk'; include Gtk

class TextEditor < Window
  def initialize
    super


    add(@text = Text.new)
    @text.set_editable(true)
    @text.set_word_wrap(true)
    @text.grab_focus
    show_all
  end
  def contents
    @text.get_chars(0,@text.get_length)
  end
end

if $0 == __FILE__
  te = TextEditor.new
  te.set_title 'Text test'
  te.signal_connect('destroy') do
    puts te.contents
    main_quit
  end
  main
end