#!/usr/bin/env ruby

require 'gtk'; include Gtk

class TextAnalyzer < Window
  def initialize
    super()

    # Create table and attach widgets to it.
    add(t = Table.new(2,4,true))
    t.border_width 5
    t.set_row_spacings 10
    t.set_col_spacings 10
    t.attach(Label.new('Enter a string: '),0,1,0,1)
    t.attach((entry = Entry.new), 1,4,0,1)
    t.attach((b_quit = Button.new('Exit')),0,1,1,2)
    t.attach((b_calc = Button.new('Analyze')),1,2,1,2)
    t.attach((result = Label.new('')),2,4,1,2)

    b_calc.signal_connect('clicked') do 
      result.set_text(analysis(entry.get_text))
      entry.grab_focus
    end

    b_quit.signal_connect('clicked') {destroy}

    entry.grab_focus
    show_all
  end

  private
  def analysis(str)
    "%d words, %d characters" %
      [str.strip.split.length, str.length]
  end
end

if $0 == __FILE__
  ta = TextAnalyzer.new
  ta.set_title 'Text analyzer'
  ta.signal_connect('destroy') {main_quit}
  main
end