#!/usr/bin/env ruby

require 'gtk'; include Gtk
require 'analyzer'

class TextAnalyzerCaller < Dialog
  def initialize
    super
    vbox.add(Label.new('This is a Gtk::Dialog instance.'))
    action_area.add(b_test = Button.new('New window'))
    b_test.signal_connect('clicked') do
      TextAnalyzer.new
    end
    action_area.add(b_quit = Button.new('Quit'))
    b_quit.signal_connect('clicked') do
      destroy # think: *what* exactly is destroyed?
    end
    show_all
  end
end

if $0 == __FILE__
  ta = TextAnalyzerCaller.new
  ta.signal_connect('destroy') {main_quit}
  main
end