#!/usr/bin/env ruby

require 'gtk' ; include Gtk

class AccelTest < Window
  def initialize
    super()
    add(vb = VBox.new(false,5))
    vb.border_width(5)
    vb.add(tb = ToggleButton.new('Click me or press F5'))
    vb.add(state = Label.new('INACTIVE'))
    vb.add(HSeparator.new)
    vb.add(b_quit = Button.new('Quit'))
    b_quit.signal_connect('clicked') {destroy}

    # Associate the F5 key with the toggle button.
    (ag = AccelGroup.new).attach(self)
    tb.add_accelerator('clicked', ag, Gdk::GDK_F5, 0, 0)

    # Link the state label to the toggle button.
    tb.signal_connect('clicked') do
      state.set_text(tb.active ? 'ACTIVE' : 'INACTIVE')
    end

    show_all
  end
end

if $0 == __FILE__
  w = AccelTest.new
  w.set_title 'Toggle test'
  w.signal_connect('destroy') {main_quit}
  main
end