#!/usr/bin/env ruby

# A simple test of binary decision trees.
# You must supply the name of a file containing training samples.

require 'bdt'

samples = BDT_set.new(ARGV[0])
tree = samples.make_tree
puts "Answer: #{tree.classify}"