#!/usr/bin/env ruby
# command line arguments: [port [label]]
require 'tk'
require 'tkchat'
require 'socket'

port, label = ARGV
listener = TCPServer.new((port||10000).to_i)
puts "Listening for incoming connection..."
socket = listener.accept
puts "Connection established."
chat = TkChat.new(socket, label||'answered')
END { chat.stop }
Tk.mainloop