#!/usr/bin/env ruby
# command line arguments: [address [port [label]]]
require 'tk'
require 'tkchat'
require 'socket'

address, port, label = ARGV
socket = TCPSocket.new(address||'localhost', (port||10000).to_i)
chat = TkChat.new(socket, label||'called')
END { chat.stop }
Tk.mainloop