#!/usr/bin/env ruby

# Un-jumbler script
#
# Accepts input from command line or from user
# Prints all words that the input can be rearranged as
#
# Relies on ispell!


def main
  input_token =
    (ARGV[0] || (print "enter a scrambled word: "; gets)).chomp
  permutations(input_token).each {|w| puts w if isword(w)}
end

def permutations( word )
  len = word.length
  if len > 1
    result = []
    len.times do |idx|
      result |=
        (permutations(word[0,idx]+word[idx+1,len-(idx+1)])).
        map{ |w| word[idx,1] + w }
    end
    result.uniq
  else 
    [word]
  end
end

def isword(s,words=nil)
  `echo #{s} | ispell -l`.chop.empty?
end

main
