#!/usr/bin/env ruby

# Alternative unjumbler that quits as soon as it finds an answer

def main
  input_token = 
    (ARGV[0] || (print "enter a scrambled word: "; gets).chomp)
  permutations(input_token) {|s| (puts s; exit) if is_word?(s)}
end

def permutations(from_word)
  if from_word.length > 1
    word = from_word
    begin
      word = word[1..-1] + word[0..0]
      permutations(word[1..-1]) {|rest| yield word[0..0] + rest}
    end until word == from_word
  else
    yield from_word
  end
end

# Substitute the file-based version of is_word? if necessary.
def is_word?(token)
  `echo #{token} | ispell -l`.chop.empty?
end

main
