#!/usr/local/bin/ruby

require 'cgi'
page = CGI.new "html3"
page.out {
  page.html {
    page.head { page.title {"A simple CGI page"} } +
    page.body {
      page.h1 {"A large header"} +
      page.p {"Text of a paragraph"} +
      page.center{ "Centered and " + page.em{"emphasized"} }
    }
  }
}
