#!/usr/local/bin/ruby

print "Content-type: text/HTML\r\n\r\n"
puts " <html>"
puts "   <head><title>A simple CGI page</title></head>"
puts "   <body><h1>A large header</h1>"
puts "     <p>Text of a paragraph</p>"
puts "     <center>Centered and <em>emphasized</em></center>"
puts "   </body>"
puts " </html>"
